- name: variables to print
  hosts: web
  vars:
   COURSE: "Devops with aws"
   DURATION: "120 hrs"
   TRAINER: "Sivakumar Reddy"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"