- name: Check if a number is less than 10
  hosts: local
  connection: local
  gather_facts: false

  vars_prompt:
    - name: number
      prompt: "Please enter a number"

  tasks:
    - name: Print the number if less than 10
      ansible.builtin.debug:
        msg: "The given number {{ number }} is less than 10"
      when: (number | int) < 10

    - name: Print the number if greater than or equal to 10
      ansible.builtin.debug:
        msg: "The given number {{ number }} is greater than or equal to 10"
      when: (number | int) >= 10
